# Generated by Django 5.1.2 on 2024-10-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='characters/')),
                ('votes_for', models.PositiveIntegerField(default=0)),
                ('votes_against', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
